import computeCarbonVariables from './bufferCarbonVariables';

test('buffer', () => {
  const surveyVariables = {
    meatAndFishConsoPerDay: '0.5',
    eggsAndDairiesConsoPerDay: '0.5',
    fruitsAndVegetablePercentageLocal: '50',
    transformedProductsConsoPerWeek: '3',
    alcoholConsoGlassPerDay: '0',
    hotDrinksConsoGlassPerDay: '0',
    juicesAndSodasConsoGlassPerDay: '2',
    categoryCarCommute: 'URBAN',
    motorTypeCarCommute: 'FUEL',
    ageCategoryCarCommute: 'TEN_YEARS_OR_YOUNGER',
    kmCarCommutePerDay: '2',
    passengersPerCarCommute: '3',
    hoursUrbanBusPerWeek: '1',
    hoursCoachCommutePerWeek: '0',
    hoursUrbanTrainPerWeek: '0',
    categoryCarTravel: 'URBAN',
    motorTypeCarTravel: 'FUEL',
    ageCategoryCarTravel: 'TEN_YEARS_OR_YOUNGER',
    kmCarTravelPerYear: '8000',
    passengersPerCarTravel: '3',
    kmCoachTravel: '0',
    kmCountryTrain: '2000',
    kmPlane: '0',
    residentsPerHousing: '3',
    housingSurfaceArea: '60',
    housingType: 'FLAT',
    maintainanceDate: 'BEFORE_1975',
    heatingSystemEnergyType: 'GAS',
    sanitoryHotWaterEnergyType: 'GAS',
    cookingAppliancesEnergyType: 'ELECTRICITY',
    electricityProvider: 'CONVENTIONAL',
    energyConsumptionKnowledge: false,
    elecKwh: '3000',
    gasKwh: '20000',
    fuelKwh: '0',
    woodKwh: '0',
    numberBigAppliances: '7',
    numberSmallAppliances: '20',
    numberBigDevices: '0',
    numberSmallDevices: '0',
    internetStreamingHoursPerWeek: '5',
    activitiesPerMonth: '0',
    clothesNewItems: 10,
  };
  const globalVariables = {
    EI_URBAN_BUS: 0.15,
    MEAN_SPEED_URBAN_BUS: 12,
    EI_COACH: 0.04,
    MEAN_SPEED_COACH: 80,

    // Food
    EI_MEAT_AND_FISH: 12.89,
    EI_RED_MEAT: 12.89,
    EI_WHITE_MEAT: 12.89,
    EI_FISH: 12.89,
    MEAT_AND_FISH_KG_PER_CONSO: 0.15,
    MEAT_AND_FISH_AVG_CONSO_KG_PER_DAY: 0.13,
    PART_OF_RED_MEAT: 0.33,
    PART_OF_WHITE_MEAT: 0.33,
    PART_OF_FISH: 0.33,

    EI_EGGS: 3.57,
    EI_DAIRIES: 3.57,
    EGGS_AND_DAIRIES_KG_PER_CONSO: 0.11,
    EGGS_AND_DAIRIES_AVG_CONSO_KG_PER_DAY: 0.22,
    PART_OF_EGGS: 0.5,
    PART_OF_DAIRIES: 0.5,

    EI_LOCAL_FRUITS_AND_VEGETABLES: 0.26,
    EI_IMPORTED_FRUITS_AND_VEGETABLES: 2.24,
    FRUITS_AND_VEGETABLES_MIN_CONSO_KG_PER_DAY: 0.16,
    FRUITS_AND_VEGETABLES_AVG_CONSO_KG_PER_DAY: 0.314,
    FRUITS_AND_VEGETABLES_FROM_MEAT_AND_FISH_SUBSTITION_PERCENTAGE: 2,
    FRUITS_AND_VEGETABLES_FROM_EGGS_AND_DAIRIES_SUBSTITION_PERCENTAGE: 2,
    FRUITS_AND_VEGETABLES_FROM_TRANSFORMED_PRODUCTS_SUBSTITION_PERCENTAGE: 2,
    EI_TRANSFORMED_PRODUCTS: 4.32,
    TRANSFORMED_PRODUCTS_KG_PER_CONSO: 0.3,
    TRANSFORMED_PRODUCTS_AVG_CONSO_KG_PER_DAY: 0.158,

    EI_STARCHES_AND_GROCERIES: 1.45,
    STARCHES_AND_GROCERIES_MIN_CONSO_KG_PER_DAY: 0.16,
    STARCHES_AND_GROCERIES_AVG_CONSO_KG_PER_DAY: 0.33,
    STARCHES_AND_GROCERIES_FROM_MEAT_AND_FISH_SUBSTITION_PERCENTAGE: 0.5,
    STARCHES_AND_GROCERIES_FROM_EGGS_AND_DAIRIES_SUBSTITION_PERCENTAGE: 0.5,
    STARCHES_AND_GROCERIES_FROM_TRANSFORMED_PRODUCTS_SUBSTITION_PERCENTAGE: 0.5,

    EI_ALCOHOL: 2.09,
    ALCOHOL_LITER_PER_GLASS: 0.3,
    EI_HOT_DRINKS: 3.08,
    HOT_DRINKS_LITER_PER_GLASS: 0.02,
    EI_JUICES_AND_SODAS: 1.47,
    JUICES_AND_SODAS_LITER_PER_GLASS: 0.2,

    MEAN_SPEED_URBAN_TRAIN: 25,
    EI_URBAN_TRAIN: 0.01,
    EI_COUNTRY_TRAIN: 0.01,
    PASSENGER_PER_TGV: 285,
    PASSENGER_PER_TER: 80,
    EI_PLANE: 0.25,
    EI_BIG_APPLIANCE: 23.3,
    EI_SMALL_APPLIANCE: 7,
    CF_WATER_HEATER: 102.872,
    EI_FURNITURES_PER_SQUARE_METER: 3.95,
    CF_FURNITURES_MIN_ONE_RESIDENT: 73.4044444,
    EI_CONSTRUCTION_HOUSE_PER_SQUARE_METER: 14.167,
    EI_CONSTRUCTION_FLAT_PER_SQUARE_METER: 17.5,
    DEPRECIATION_DURATION: 30,
    EI_MAINTENANCE_PER_SQUARE_METER: 0.694,
    EI_WATER_PER_LITER: 0.000168,
    WATER_CONSO_LITER_PER_YEAR_PER_PERSON: 54020,
    EI_CONVENTIONAL_ELEC_PER_KWH: 0.116,
    EI_ALTERNATIVE_ELEC_PER_KWH: 0.013,
    EI_GAS_PER_KWH: 0.227,
    EI_FUEL_OIL_PER_KWH: 0.323,
    EI_WOOD_PER_KWH: 0.03,
    LIGHTING_AND_ELECTRICAL_APPLIANCES_CONSO_KWH_PER_PERSON_PER_YEAR: 1062.4,
    SANITARY_HOT_WATER_CONSO_KWH_PER_PERSON_PER_YEAR: 711.4,
    COOKING_APPLIANCES_KWH_PER_PERSON_PER_YEAR: 346.4,
    SANITARY_HOT_WATER_REDUCTION_PERCENTAGE_PER_PERSON: 0.05,
    COOKING_APPLIANCES_REDUCTION_PERCENTAGE_PER_PERSON: 0.2,
    LIGHTING_AND_ELECTRICAL_APPLIANCES_REDUCTION_PERCENTAGE_PER_PERSON: 0,
    EI_INTERNET_STREAMING: 0.125,
    CF_INTERNET_OTHERS: 48.66,
    EI_BIG_DEVICES: 47.8,
    EI_SMALL_DEVICES: 12.5,
    CF_SERVICES_GAS: 70.19,
    CF_SERVICES_ELECTRICITY: 62.88,
    CF_GOODS_AND_SERVICES_WITHOUT_ENERGY: 211.92,
    EI_ACTIVITIES_GAS: 0.74,
    EI_ACTIVITIES_ELEC: 0.66,
    EI_ACTIVITIES_WITHOUT_ENERGY: 0.66,
    EI_CLOTHES_PER_ITEM: 22.38,

    EI_HOUSING_PER_SURFACE_AREA: {
      HOUSE: {
        BEFORE_1975: 232.5,
        BETWEEN_1975_AND_2000: 142.5,
        AFTER_2000: 72.5,
      },
      FLAT: {
        BEFORE_1975: 205.1,
        BETWEEN_1975_AND_2000: 115.1,
        AFTER_2000: 45.1,
      },
    },
    EI_CAR: {
      URBAN: {
        FUEL: 0.232,
        ELECTRIC: 0.09915,
        HYBRID: 0.171,
      },
      BIG: {
        FUEL: 0.2665,
        ELECTRIC: 0.139,
        HYBRID: 0.2245,
      },
      SPORT: {
        FUEL: 0.344,
        ELECTRIC: 0.3125,
        HYBRID: 0.3125,
      },
      LOW_CARBON: {
        FUEL: 0.1,
        ELECTRIC: 0.1,
        HYBRID: 0.1,
      },
    },
    MOTOR_AGING_FACTOR: {
      FUEL: {
        TEN_YEARS_OR_YOUNGER: 0.943292608,
        BEETWEEN_TEN_AND_FIFTEEN_YEARS: 1.101343381,
        FIFTEEN_YEARS_OR_OLDER: 1.164876711,
      },
      ELECTRIC: {
        TEN_YEARS_OR_YOUNGER: 1,
        BEETWEEN_TEN_AND_FIFTEEN_YEARS: 1,
        FIFTEEN_YEARS_OR_OLDER: 1,
      },
      HYBRID: {
        TEN_YEARS_OR_YOUNGER: 1,
        BEETWEEN_TEN_AND_FIFTEEN_YEARS: 1,
        FIFTEEN_YEARS_OR_OLDER: 1,
      },
    },
    CF_GAS_SERVICES: 336,
    CF_ELEC_SERVICES: 301,
    CF_OTHER_SERVICES: 363,
  };
  const res = computeCarbonVariables(surveyVariables, globalVariables);
  expect(res).toStrictEqual({});
});
