const surveyVariablesSchema = {
  type: 'object',
  properties: {
    meatAndFishConsoPerDay: { type: 'number', default: 0 },
    eggsAndDairiesConsoPerDay: { type: 'number', default: 0 },
    fruitsAndVegetablePercentageLocal: { type: 'number', default: 0 },
    transformedProductsConsoPerWeek: { type: 'number', default: 0 },
    alcoholConsoGlassPerDay: { type: 'number', default: 0 },
    hotDrinksConsoGlassPerDay: { type: 'number', default: 0 },
    juicesAndSodasConsoGlassPerDay: { type: 'number', default: 0 },
    categoryCarCommute: {
      type: 'string',
      enum: ['SPORT', 'BIG', 'URBAN', 'LOW_CARBON'],
      default: 'URBAN',
    },
    motorTypeCarCommute: {
      type: 'string',
      enum: ['HYBRID', 'FUEL', 'ELECTRIC'],
      default: 'FUEL',
    },
    ageCategoryCarCommute: {
      type: 'string',
      enum: [
        'TEN_YEARS_OR_YOUNGER',
        'BEETWEEN_TEN_AND_FIFTEEN_YEARS',
        'FIFTEEN_YEARS_OR_OLDER',
      ],
      default: 'BEETWEEN_TEN_AND_FIFTEEN_YEARS',
    },
    kmCarCommutePerDay: { type: 'number', default: 0 },
    passengersPerCarCommute: { type: 'number', default: 1 },
    hoursUrbanBusPerWeek: { type: 'number', default: 0 },
    hoursCoachCommutePerWeek: { type: 'number', default: 0 },
    hoursUrbanTrainPerWeek: { type: 'number', default: 0 },
    categoryCarTravel: {
      type: 'string',
      enum: ['SPORT', 'BIG', 'URBAN', 'LOW_CARBON'],
      default: 'URBAN',
    },
    motorTypeCarTravel: {
      type: 'string',
      enum: ['HYBRID', 'FUEL', 'ELECTRIC'],
      default: 'FUEL',
    },
    ageCategoryCarTravel: {
      type: 'string',
      enum: [
        'TEN_YEARS_OR_YOUNGER',
        'BEETWEEN_TEN_AND_FIFTEEN_YEARS',
        'FIFTEEN_YEARS_OR_OLDER',
      ],
      default: 'BEETWEEN_TEN_AND_FIFTEEN_YEARS',
    },
    kmCarTravelPerYear: { type: 'number', default: 0 },
    passengersPerCarTravel: { type: 'number', default: 0 },
    kmCoachTravel: { type: 'number', default: 0 },
    kmCountryTrain: { type: 'number', default: 0 },
    kmPlane: { type: 'number', default: 0 },
    residentsPerHousing: { type: 'number', default: 1 },
    housingSurfaceArea: { type: 'number', default: 0 },
    housingType: {
      type: 'string',
      enum: ['HOUSE', 'FLAT'],
      default: 'HOUSE',
    },
    maintainanceDate: {
      type: 'string',
      enum: ['BEFORE_1975', 'BETWEEN_1975_AND_2000', 'AFTER_2000'],
      default: 'BETWEEN_1975_AND_2000',
    },
    heatingSystemEnergyType: {
      type: 'string',
      enum: ['GAS', 'FUEL_OIL', 'ELECTRICITY', 'HEATING_NETWORK', 'WOOD'],
      default: 'GAS',
    },
    sanitoryHotWaterEnergyType: {
      type: 'string',
      enum: ['GAS', 'FUEL_OIL', 'ELECTRICITY', 'HEATING_NETWORK', 'WOOD'],
      default: 'ELECTRICITY',
    },
    cookingAppliancesEnergyType: {
      type: 'string',
      enum: ['GAS', 'FUEL_OIL', 'ELECTRICITY', 'HEATING_NETWORK', 'WOOD'],
      default: 'ELECTRICITY',
    },
    electricityProvider: {
      type: 'string',
      enum: ['ALTERNATIVE', 'CONVENTIONAL'],
      default: 'CONVENTIONAL',
    },
    heatingNetworkName: { type: ['string', 'null'] },
    energyConsumptionKnowledge: { type: 'boolean', default: false },
    elecKwh: { type: 'number', default: 0 },
    gasKwh: { type: 'number', default: 0 },
    fuelKwh: { type: 'number', default: 0 },
    woodKwh: { type: 'number', default: 0 },
    heatingNetworkKwh: { type: 'number', default: 0 },
    numberBigAppliances: { type: 'number', default: 0 },
    numberSmallAppliances: { type: 'number', default: 0 },
    numberBigDevices: { type: 'number', default: 0 },
    numberSmallDevices: { type: 'number', default: 0 },
    internetStreamingHoursPerWeek: { type: 'number', default: 0 },
    clothesNewItems: { type: 'number', default: 0 },
    activitiesPerMonth: { type: 'number', default: 0 },
  },
};

export default surveyVariablesSchema;
